=== batinkov/emtf_cell/cactusprojects/emtf/hal_pciexpr/examples/XMLAddressTable/HardwareAddressTable-ver-2-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by schwick (cern) -->
<!--W3C Schema generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="ADDRESSType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" fixed="number"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="ADDRESS_MODIFIERType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="number"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="BASE_ADDRESSType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="number"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="CARD_IDType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="VENDORType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="DEVICEType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="CARD_TYPE">
		<xs:complexType>
			<xs:choice>
				<xs:element name="VME_ADDRESS" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="VME_ADDRESSType">
								<xs:attribute name="_userInfo" type="xs:string" use="optional"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="VME64X_ADDRESS" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="VME64X_ADDRESSType">
								<xs:attribute name="_userInfo" type="xs:string" use="optional"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PCI_ADDRESS" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="PCI_ADDRESSType">
								<xs:attribute name="_userInfo" type="xs:string" use="optional"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="_type" type="xs:string" use="required" fixed="Module"/>
			<xs:attribute name="TYPE_ID" type="xs:string" use="optional"/>
			<xs:attribute name="_userInfo" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CURRENT_USERType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="DESCRIPTIONType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="LOCATIONType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="MASKType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="number"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="READ_OR_WRITEType">
		<xs:simpleContent>
			<xs:extension base="READ_OR_WRITESimpleType">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="READ_OR_WRITESimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="r"/>
			<xs:enumeration value="rw"/>
			<xs:enumeration value="w"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="BARType">
		<xs:simpleContent>
			<xs:extension base="BARimpleType">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="number"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="MAPType">
		<xs:simpleContent>
			<xs:extension base="MAPimpleType">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="number"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="BARimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
			<xs:enumeration value="4"/>
			<xs:enumeration value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MAPimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
			<xs:enumeration value="4"/>
			<xs:enumeration value="5"/>
			<xs:enumeration value="6"/>
			<xs:enumeration value="7"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SPACEType">
		<xs:simpleContent>
			<xs:extension base="SPACEimpleType">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="SPACEimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="memory"/>
			<xs:enumeration value="configuration"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="USERSType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="USER_COMMENTType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="VME64X_ADDRESSType">
		<xs:all>
			<xs:element name="ADDRESS" type="ADDRESSType"/>
			<xs:element name="READ_OR_WRITE" type="READ_OR_WRITEType"/>
			<xs:element name="SPACE" type="SPACEType"/>
			<xs:element name="MAP" type="MAPType"/>
			<xs:element name="MASK" type="MASKType"/>
			<xs:element name="WIDTH" type="WIDTHType" minOccurs="0"/>
			<xs:element name="DESCRIPTION" type="DESCRIPTIONType" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="_type" type="xs:string" use="required" fixed="Module"/>
		<xs:attribute name="ITEM_NAME" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="VME_ADDRESSType">
		<xs:all>
			<xs:element name="ADDRESS" type="ADDRESSType"/>
			<xs:element name="ADDRESS_MODIFIER" type="ADDRESS_MODIFIERType"/>
			<xs:element name="READ_OR_WRITE" type="READ_OR_WRITEType"/>
			<xs:element name="WIDTH" type="WIDTHType"/>
			<xs:element name="MASK" type="MASKType"/>
			<xs:element name="DESCRIPTION" type="DESCRIPTIONType" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="_type" type="xs:string" use="required" fixed="Module"/>
		<xs:attribute name="ITEM_NAME" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PCI_ADDRESSType">
		<xs:all>
			<xs:element name="ADDRESS" type="ADDRESSType"/>
			<xs:element name="BAR" type="BARType"/>
			<xs:element name="SPACE" type="SPACEType"/>
			<xs:element name="READ_OR_WRITE" type="READ_OR_WRITEType"/>
			<xs:element name="MASK" type="MASKType"/>
			<xs:element name="DESCRIPTION" type="DESCRIPTIONType" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="_type" type="xs:string" use="required" fixed="Module"/>
		<xs:attribute name="ITEM_NAME" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="VME_CARDType">
		<xs:all>
			<xs:element name="BASE_ADDRESS" type="BASE_ADDRESSType"/>
			<xs:element name="CARD_ID" type="CARD_IDType"/>
			<xs:element name="CURRENT_USER" type="CURRENT_USERType"/>
			<xs:element name="USER_COMMENT" type="USER_COMMENTType"/>
			<xs:element name="LOCATION" type="LOCATIONType"/>
		</xs:all>
		<xs:attribute name="_type" type="xs:string" use="required" fixed="Module"/>
		<xs:attribute name="SERIAL_NUMBER" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="PCI_CARDType">
		<xs:all>
			<xs:element name="VENDOR" type="VENDORType"/>
			<xs:element name="DEVICE" type="DEVICEType"/>
			<xs:element name="CARD_ID" type="CARD_IDType"/>
			<xs:element name="CURRENT_USER" type="CURRENT_USERType"/>
			<xs:element name="USER_COMMENT" type="USER_COMMENTType"/>
			<xs:element name="LOCATION" type="LOCATIONType"/>
		</xs:all>
		<xs:attribute name="_type" type="xs:string" use="required" fixed="Module"/>
		<xs:attribute name="SERIAL_NUMBER" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="WIDTHType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="_type" type="xs:string" use="required" fixed="number"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== batinkov/emtf_cell/cactusprojects/emtf/hal_pciexpr/generic/classtester/src/linux/x86/VME64xTable_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML file generated by from VME64xTable_1.txt-->
<CARD_TYPE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HardwareAddressTable-ver-2-1.xsd" _type="Module" TYPE_ID="vme64x-2">
<!--  ******************************************************************************************************  --> 
<!--  *                   VME64x Address Table : for test purpose  --> 
<!--  *                         item       AdrSpace  map AM  width   address      mask  r  w fl  description  --> 
<!--  ******************************************************************************************************  --> 
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem1">
		<ADDRESS _type="number">0x00000103</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">r</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
		<DESCRIPTION _type="string">a comment</DESCRIPTION>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem2">
		<ADDRESS _type="number">0x00000107</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">r</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
		<DESCRIPTION _type="string">a somewhat longer comment</DESCRIPTION>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem3">
		<ADDRESS _type="number">0x0000010b</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">r</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem4">
		<ADDRESS _type="number">0x00000800</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">r</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem5">
		<ADDRESS _type="number">0x00000810</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">r</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem6">
		<ADDRESS _type="number">0x00000820</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">r</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem7">
		<ADDRESS _type="number">0x0007fffb</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-confItem8">
		<ADDRESS _type="number">0x0007ffff</ADDRESS>
		<SPACE _type="string">configuration</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">r</READ_OR_WRITE>
		<MASK _type="number">0x000000ff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-item1">
		<ADDRESS _type="number">0x00000000</ADDRESS>
		<SPACE _type="string">memory</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<MASK _type="number">0xffffffff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-item2">
		<ADDRESS _type="number">0x00000010</ADDRESS>
		<SPACE _type="string">memory</SPACE>
		<MAP _type="number">0</MAP>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<MASK _type="number">0xffffffff</MASK>
		<DESCRIPTION _type="string">next has empty</DESCRIPTION>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-item3">
		<ADDRESS _type="number">0x00000000</ADDRESS>
		<SPACE _type="string">memory</SPACE>
		<MAP _type="number">1</MAP>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<MASK _type="number">0xffffffff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-item4">
		<ADDRESS _type="number">0x00000010</ADDRESS>
		<SPACE _type="string">memory</SPACE>
		<MAP _type="number">1</MAP>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<MASK _type="number">0xffffffff</MASK>
	</VME64X_ADDRESS>
	<VME64X_ADDRESS _type="Module" ITEM_NAME="vme64x-map1-item5">
		<ADDRESS _type="number">0x00000000</ADDRESS>
		<SPACE _type="string">memory</SPACE>
		<MAP _type="number">2</MAP>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<MASK _type="number">0x00000080</MASK>
	</VME64X_ADDRESS>
</CARD_TYPE>

=== batinkov/emtf_cell/cactusprojects/emtf/daq/hal/generic/classtester/src/linux/x86/VMETable_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML file generated by from VMETable_1.txt-->
<CARD_TYPE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HardwareAddressTable-ver-2-1.xsd" _type="Module" TYPE_ID="vme-2">
<!--  ******************************************************************************************************  --> 
<!--  *                   VME64x Address Table : for test purpose  --> 
<!--  *                         item       AdrSpace  map AM  width   address      mask  r  w fl  description  --> 
<!--  ******************************************************************************************************  --> 
	<VME_ADDRESS _type="Module" ITEM_NAME="vme-map1-item1">
		<ADDRESS _type="number">0x00000000</ADDRESS>
		<ADDRESS_MODIFIER _type="number">0x39</ADDRESS_MODIFIER>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<WIDTH _type="number">4</WIDTH>
		<MASK _type="number">0xffffffff</MASK>
		<DESCRIPTION _type="string">This is the first item</DESCRIPTION>
	</VME_ADDRESS>
	<VME_ADDRESS _type="Module" ITEM_NAME="vme-map1-item2">
		<ADDRESS _type="number">0x00000010</ADDRESS>
		<ADDRESS_MODIFIER _type="number">0x09</ADDRESS_MODIFIER>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<WIDTH _type="number">4</WIDTH>
		<MASK _type="number">0xffffffff</MASK>
		<DESCRIPTION _type="string">This is a comment</DESCRIPTION>
	</VME_ADDRESS>
	<VME_ADDRESS _type="Module" ITEM_NAME="vme-map1-item3">
		<ADDRESS _type="number">0x00000000</ADDRESS>
		<ADDRESS_MODIFIER _type="number">0x10</ADDRESS_MODIFIER>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<WIDTH _type="number">4</WIDTH>
		<MASK _type="number">0xffffffff</MASK>
		<DESCRIPTION _type="string">no comment</DESCRIPTION>
	</VME_ADDRESS>
	<VME_ADDRESS _type="Module" ITEM_NAME="vme-map1-item4">
		<ADDRESS _type="number">0x00000010</ADDRESS>
		<ADDRESS_MODIFIER _type="number">0x19</ADDRESS_MODIFIER>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<WIDTH _type="number">4</WIDTH>
		<MASK _type="number">0xffffffff</MASK>
	</VME_ADDRESS>
	<VME_ADDRESS _type="Module" ITEM_NAME="vme-map1-item5">
		<ADDRESS _type="number">0x00000000</ADDRESS>
		<ADDRESS_MODIFIER _type="number">0x39</ADDRESS_MODIFIER>
		<READ_OR_WRITE _type="string">rw</READ_OR_WRITE>
		<WIDTH _type="number">4</WIDTH>
		<MASK _type="number">0x00000080</MASK>
	</VME_ADDRESS>
</CARD_TYPE>
